# http://travis-ci.org/#!/gjhiggins/RDFAlchemy
language: python
python:
    - 3.6
    - pypy
install:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' || $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install --use-mirrors --allow-unverified elementtree --allow-all-external --default-timeout 60 "elementtree"; fi
    - pip install -r requirements.txt --allow-all-external
    - python setup.py build

before_script:
    # - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then flake8 rdfalchemy; fi

script:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' || $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then SESAME2_URL="http://bel-epa.com:8080/openrdf-workbench/repositories/otter/query" nosetests; fi
    # Must cd somewhere else ("build/src" in this instance) so Python3 doesn't
    # get confused and run the Python 2 code from the current directory
    # instead of the installed 2to3 translated version.
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then SESAME2_URL="http://bel-epa.com:8080/openrdf-workbench/repositories/otter/query" nosetests --where=build/src; fi
