# http://travis-ci.org/#!/gjhiggins/RDFAlchemy
language: python
python:
    - 3.7
      dist: xenial
      sudo: true
install:
    - pip install -r requirements.txt --allow-all-external
    - python setup.py build

script:
    - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then SESAME2_URL="http://bel-epa.com:8080/openrdf-workbench/repositories/otter/query" nosetests --where=build/src; fi
